_wandb:
    value:
        cli_version: 0.22.2
        e:
            nr5jcucs3mmji4dyokxdjcan89k0s0sz:
                args:
                    - -c
                    - configs/deim_dfine/deim_hgnetv2_x_coco_5shot.yml
                    - -t
                    - weights/deim_dfine_hgnetv2_x_coco_50e.pth
                codePath: train.py
                codePathLocal: train.py
                cpu_count: 16
                cpu_count_logical: 32
                cudaVersion: "12.9"
                disk:
                    /:
                        total: "1965172678656"
                        used: "1421871517696"
                email: bragin1703@gmail.com
                executable: /usr/bin/python
                git:
                    commit: 8f28fe63cca4bd2a0f4abaf9b0814b69d5abb658
                    remote: https://github.com/Intellindust-AI-Lab/DEIM
                gpu: NVIDIA GeForce RTX 5090
                gpu_count: 1
                gpu_nvidia:
                    - architecture: Blackwell
                      cudaCores: 21760
                      memoryTotal: "34190917632"
                      name: NVIDIA GeForce RTX 5090
                      uuid: GPU-72253c0e-957c-2323-3ebc-6b878ac9c1ad
                host: cc383fd63add
                memory:
                    total: "134986223616"
                os: Linux-6.8.0-78-generic-x86_64-with-glibc2.35
                program: /root/DEIM/train.py
                python: CPython 3.10.12
                root: /root/DEIM
                startedAt: "2025-10-15T17:01:08.926530Z"
                writerId: nr5jcucs3mmji4dyokxdjcan89k0s0sz
        m: []
        python_version: 3.10.12
        t:
            "1":
                - 1
                - 5
                - 11
                - 41
                - 49
                - 53
                - 71
            "2":
                - 1
                - 5
                - 11
                - 41
                - 49
                - 53
                - 71
            "3":
                - 2
                - 13
                - 16
            "4": 3.10.12
            "5": 0.22.2
            "6": 4.50.3
            "12": 0.22.2
            "13": linux-x86_64
config_file:
    value: configs/deim_dfine/deim_hgnetv2_x_coco_5shot.yml
device:
    value: null
output_dir:
    value: null
seed:
    value: null
use_amp:
    value: false
